Repository Azure-Samples/contoso-real-estate, pull requests merged in 2023-09, with the labels that each got.

#323 Style:Logos-added-register-page-#292
  packages/portal/package.json
  packages/portal/src/app/authentication/authentication.component.html
  packages/portal/src/app/authentication/authentication.component.scss
  packages/portal/src/app/authentication/authentication.component.ts
  packages/portal/src/index.html
Labels: Hack-together, Hack-together:awaiting-feedback, Hack-together: pending-final-review

#233 feat(portal): bind routed information to routed component inputs
  packages/portal/src/app/app.config.ts
  packages/portal/src/app/authentication/authentication.component.ts
  packages/portal/src/app/checkoutpage/checkoutpage.component.html
  packages/portal/src/app/checkoutpage/checkoutpage.component.ts
  packages/portal/src/app/profile/profile.component.html
  packages/portal/src/app/profile/profile.component.ts
  packages/portal/src/app/rentalpage/rentalpage.component.ts
Labels: status: blocked, scope: portal

#355 fix: unequal sizes of listing cards on the homepage.
  package-lock.json
  packages/portal/src/app/app.component.scss
  packages/portal/src/app/profile/profile.component.scss
  packages/portal/src/app/shared/card/card.component.scss
  packages/portal/src/styles/styles.scss
Labels: Hack-together, Hack-together:accepted
