Repository Azure-Samples/contoso-real-estate, pull requests merged in 2023-08, with the labels that each got.

#261 fix: secrets naming
  infra/app/blog.bicep
  infra/app/cms.bicep
  infra/app/stripe.bicep
Labels: scope: deployments, scope: infra

#270 chore: create hack-together.md
  .github/ISSUE_TEMPLATE/hack-together.md
Labels: Hack-together

#268 chore(infra): make stripe keys optional
  infra/app/stripe.bicep
Labels: scope: infra

#269 Completed: chore/add-docs-to-README
  README.md
  assets/screenshots/contoso-docs-website-preview.png
  assets/screenshots/contoso-docs-website-testreport.png
Labels: docs-site

#298 fix: fixed typo in contrubuting.md
  CONTRIBUTING.md
Labels: Hack-together, Hack-together:accepted

#284 fix: fix typo in reservations list
  packages/portal/src/app/profile/profile.component.html
Labels: Hack-together, Hack-together:accepted

#275 fix(portal): issue #260 fixed the responsive design for mobile in the 'view listing page'
  packages/portal/src/app/rentalpage/rentalpage.component.scss
  packages/portal/src/app/shared/booking-form/booking-form.component.scss
Labels: Hack-together, Hack-together:accepted

#287 fix: fixed Blurred Booking Options Accessible #252
  packages/portal/src/app/shared/booking-form/booking-form.component.html
  packages/portal/src/app/shared/booking-form/booking-form.component.scss
Labels: Hack-together, Hack-together:accepted

#310 docs: update global readme.md with `azd auth login` additional params
  README.md
Labels: Hack-together, Hack-together:awaiting-feedback

#312 docs: fix typos in README files
  README.md
  packages/api/README.md
  packages/docs/README.md
  packages/portal/README.md
Labels: Hack-together, Hack-together:accepted

#300 feat: Create sharing menu
  packages/portal/src/app/rentalpage/rentalpage.component.html
  packages/portal/src/app/rentalpage/rentalpage.component.ts
  packages/portal/src/app/shared/listing.service.ts
Labels: Hack-together, Hack-together:accepted

#305 feat(portal): implement 404 page
  .vscode/extensions.json
  .vscode/tasks.json
  packages/portal/src/app/shared/errors/not-found/not-found.component.html
  packages/portal/src/app/shared/errors/not-found/not-found.component.scss
  packages/portal/src/app/shared/errors/not-found/not-found.component.ts
Labels: Hack-together, Hack-together:awaiting-feedback

#309 chore: add batch call to get api/favorites
  packages/portal/src/app/shared/favorite-button/favorite-button/favorite-button.component.ts
Labels: Hack-together, Hack-together:accepted
